[package]
name = "weatherforecast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
reqwest = "0.11.6"
tokio = "1.11.0"